version: '3'
name: todo-container

volumes:
  todo-db:

services:
  todo-app:
    image: barney003/todo
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://todo-db:3306/todo_db?useMysqlMetadata=true
    ports:
      - "8081:8081"
    depends_on:
      - todo-db
  todo-db:
    image: barney003/todo-db
    ports:
      - "3306:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_USER=todo_user
      - MARIADB_PASSWORD=todo_user
      - MARIADB_DATABASE=todo_db
    volumes:
      - todo-db:/var/lib/mysql
      - ./artifact:/docker-entrypoint-initdb.d
