-- Create Database Scheme
CREATE DATABASE IF NOT EXISTS todo_db;

-- Create User
CREATE USER IF NOT EXISTS 'todo_user'@'%' IDENTIFIED BY 'todo_user';
GRANT ALL PRIVILEGES ON todo_db.* TO 'todo_user'@'%';
FLUSH PRIVILEGES;

USE todo_db;

-- Create Table
CREATE TABLE IF NOT EXISTS user (
	USERNAME VARCHAR(255) PRIMARY KEY NOT NULL,
	PASSWORD VARCHAR(100),
	FULL_NAME VARCHAR(255),
	USER_STATUS VARCHAR(100) NOT NULL DEFAULT 'A',
	MODIFIED INT NOT NULL DEFAULT 0,
	CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS user_attribute (
	USERNAME VARCHAR(255) PRIMARY KEY NOT NULL,
	PROVIDER VARCHAR(50) NOT NULL,
	MODIFIED INT NOT NULL DEFAULT 0,
	CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	
	CONSTRAINT `fk_user_attribute_username` FOREIGN KEY (USERNAME) REFERENCES user (USERNAME) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS todo_item (
	ITEM_ID BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	USERNAME VARCHAR(255) NOT NULL,
	ITEM_TITLE VARCHAR(100) NOT NULL,
	ITEM_DESC TEXT,
	ITEM_STATUS VARCHAR(100) NOT NULL DEFAULT 'I',
	MODIFIED INT NOT NULL DEFAULT 0,
	CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	
	CONSTRAINT `fk_todo_item_username` FOREIGN KEY (USERNAME) REFERENCES user (USERNAME) ON DELETE CASCADE ON UPDATE CASCADE
);

-- Triggers
DELIMITER //
CREATE TRIGGER `BEFORE_UPD_USER` BEFORE UPDATE ON `user` FOR EACH ROW BEGIN
   SET NEW.UPDATED_AT = CURRENT_TIMESTAMP();
   SET NEW.MODIFIED = OLD.MODIFIED + 1;
END
//

CREATE TRIGGER `BEFORE_UPD_USER_ATTRIBUTE` BEFORE UPDATE ON `user_attribute` FOR EACH ROW BEGIN
   SET NEW.UPDATED_AT = CURRENT_TIMESTAMP();
   SET NEW.MODIFIED = OLD.MODIFIED + 1;
END
//

CREATE TRIGGER `BEFORE_UPD_TODO_ITEM` BEFORE UPDATE ON `todo_item` FOR EACH ROW BEGIN
   SET NEW.UPDATED_AT = CURRENT_TIMESTAMP();
   SET NEW.MODIFIED = OLD.MODIFIED + 1;
END
//
DELIMITER ;

-- Indexing
CREATE INDEX todo_item_item_title_idx ON todo_item(ITEM_TITLE);
CREATE INDEX todo_item_item_status_idx ON todo_item(ITEM_STATUS);